"""Rule-ID registry (plan §3). Tests reference these IDs; unknown IDs are an error."""

from __future__ import annotations

from types import MappingProxyType

RULES: MappingProxyType[str, str] = MappingProxyType(
    {
        "MKT-01": "M1 execution, M5 context",
        "MKT-02": "only finalized M5 for gates",
        "MKT-03": "Cross 10x verified from exchange",
        "MKT-04": "collector always on; raw trades + finalized OHLCV",
        "MKT-05": "M5 aggregated from canonical M1",
        "PG-01": "bullish P-Gap: Low[i+1] > High[i-1] strict",
        "PG-02": "bearish P-Gap: High[i+1] < Low[i-1] strict",
        "PG-03": "P-Gap on finalized candles only",
        "SEQ-01": "long continuation: Low[n] >= Low[n-1]",
        "SEQ-02": "short continuation: High[n] <= High[n-1]",
        "SEQ-03": "no candle-color gate",
        "SPK-01": "first valid directional P-Gap confirms Spike at right-candle close",
        "SPK-02": "Origin backtracking; stop at violation/missing; freeze",
        "SPK-03": "LastSpikeCandle init = right candle; updated by structural extension",
        "SPK-04": "SpikeExtreme / SpikeRange over Origin..LastSpike",
        "E1-01": "E1 long = Low(LastSpike), short = High(LastSpike), LIMIT",
        "E1-02": "E1 only after Context, Exhaustion and Risk pass",
        "E1-03": "reprice guard: NEW and executedQty==0 and setup_position_qty==0",
        "E1-04": "11-step M1-close reprice procedure",
        "E1-05": "fill discovered in race aborts replacement -> protection",
        "E1-06": "replacement only after old E1 inactive + zero fill + zero position",
        "E1-07": "any fill freezes E1 price for the setup",
        "E1-08": "partial remainder stays at original E1 through FillWindow",
        "E1-09": "no retroactive fills",
        "E1-10": "uncertain state -> no replacement / ERROR_HOLD",
        "PB-01": "PullbackStart: live price <= E1 (long) / >= E1 (short); freezes reprice",
        "PB-02": "Live fill truth = exchange status",
        "FW-01": "FillWindow #1 = PB candle; close of #4 zero fill -> EXPIRED_NO_FILL",
        "FW-02": "partial at #4 -> cancel remainder, keep protected, E2 off",
        "SLTP-01": "SL long = OriginLow - tick; short = OriginHigh + tick",
        "SLTP-02": "R = abs(E1-SL); single TP = E1 +/- R",
        "SLTP-03": "no TP2 / partial TP / AB=CD / trailing anywhere",
        "SLTP-04": "protect executed quantity immediately",
        "E2-01": "E2 = (E1+SL)/2, Qty = Qty(E1), same SL and TP",
        "E2-02": "E2 only after full E1 + reconciled position + verified protection",
        "E2-03": "E2 no candle expiry; no exit recomputation from average entry",
        "E2-04": "E2 same-direction add; reduceOnly=false only if runtime-validated",
        "E2-05": "E2 unsafe -> continue without E2",
        "CAP-01": "two logical slots per market; no second setup",
        "CTX-01": "latest finalized M5 with close_time <= evaluation time",
        "CTX-02": "V6.0: < warmup M5 bars (30) -> CONTEXT_UNKNOWN_WARMUP; NetTP still evaluated",
        "CTX-03": "2L/2R strict pivots confirmed after i+2 closes",
        "CTX-04": "V6.0: dual pivot -> HTFAligned false (no global reject)",
        "CTX-05": "M5 trend BULL/BEAR/NEUTRAL(_INSUFFICIENT_STRUCTURE)",
        "CTX-06": "ADX14 Wilder",
        "CTX-07": "CHOP14 (informational since V6.0)",
        "CTX-08": "regime precedence RANGE, TREND, TRANSITION (informational since V6.0)",
        "CTX-09": "Range14 inclusive; raw RangePosition for logic",
        "CTX-10": "RangeMiddle (informational since V6.0)",
        "CTX-11": "B ChannelEdge: origin RP <= 1/3 (Long) / >= 2/3 (Short), any regime",
        "CTX-12": "A LevelBreak: strict Spike M1 close beyond an eligible M5 level",
        "CTX-13": "C HTFAligned: M5 trend BULL (Long) / BEAR (Short), any regime",
        "CTX-14": "HTF opposite without breakout (informational since V6.0)",
        "CTX-15": "V6.0: PASS iff NetTP > 0 AND (A OR B OR C); else NO_VALID_CONTEXT",
        "CTX-16": "RoomToTP (informational since V6.0)",
        "CTX-17": "liquidity measure prev-20 median (informational since V6.0)",
        "CTX-18": "D NetTP: |TP-E1| - E1*entry - TP*exit > 0; no costs -> CONTEXT_NET_TP_UNKNOWN",
        "CTX-19": "re-evaluate before every zero-fill E1 submit/replace",
        "CTX-20": "context never closes/moves a filled position",
        "EXH-01": "ATR14_M5 Wilder",
        "EXH-02": "EMA20_M5 SMA-seeded, restart-stable",
        "EXH-03": "TrendAgeBars",
        "EXH-04": "MicrochannelLen",
        "EXH-05": "StretchATR",
        "EXH-06": "SpikeATR",
        "EXH-07": "RangePosition20; zero range fail closed",
        "EXH-08": "OpposingSwingDistanceATR; none = +INF",
        "EXH-09": "exhaustion conditions; equality triggers",
        "EXH-10": "FreshBreakoutException",
        "EXH-11": "exhaustion expression + sub-reasons (V6.0: advisory, ADVISORY_WOULD_REJECT)",
        "EXH-12": "V6.0: exhaustion recorded after Context but never gates",
        "RSK-01": "complete setup worst-case <= 1% wallet incl. costs",
        "RSK-02": "qty rounded down to step; recomputed every revision",
        "RSK-03": "liquidation >= 1R beyond SL; no foreign formula",
        "RSK-04": "unvalidated safety -> reject / disable E2 or Live",
        "TAB-01": "verify official Tabdeal docs; no undocumented behavior",
        "TAB-02": "idempotency ids; retries never duplicate",
        "TAB-03": "restart reconciliation before any order",
        "TAB-04": "ambiguity -> ERROR_HOLD",
        "LIVE-01": "LIVE_AUTOMATION_DISABLED until checklist passes",
        "SHD-01": "Shadow initial wallet 100 USDT",
        "SHD-02": "one canonical engine for all modes",
        "SHD-03": "causal event order per M1 bucket",
        "SHD-04": "shadow fill rules (raw trades / OHLC)",
        "SHD-05": "same-bar TP/SL ambiguous -> worst case",
        "SHD-06": "counterfactual isolated and labeled",
        "GOV-01": "no ML / online learning / tuning / rule mutation",
        "GOV-02": "spec precedence; contradictions are BLOCKERS",
        "DATA-01": "PostgreSQL with migrations",
        "DATA-02": "candidate stores metrics, gates, reasons, spec version, ts, candle ids",
        "DATA-03": "rejected candidates never deleted",
        "UI-01": "ui-ux-pro-max",
        "UI-02": "frontend display-only",
        "ANL-01": "analytics only; no automatic parameter selection",
    }
)


def require(rule_id: str) -> str:
    if rule_id not in RULES:
        raise KeyError(f"unknown rule id {rule_id}")
    return rule_id
